apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/committer: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/contextDir: /simulator
    commit.image.appsody.dev/date: Tue Jul 7 07:41:42 2020 -0700
    commit.image.appsody.dev/message: add back reefer repo to create data at rest
    commit.stack.appsody.dev/author: Kamran Shamsi <45264227+Kamran64@users.noreply.github.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/python-flask
    commit.stack.appsody.dev/date: Wed Apr 1 11:38:29 2020 +0100
    commit.stack.appsody.dev/message: Bump stack version to put src and image in the
      index (#736)
    image.opencontainers.org/created: "2020-07-29T18:46:20-07:00"
    image.opencontainers.org/documentation: https://github.ibm.com/vaccine-cold-chain/reeferiotsimulator
    image.opencontainers.org/revision: ca6a9cfaf01adf46823f01d113c8484c0f1fdc58-modified
    image.opencontainers.org/source: https://github.ibm.com/vaccine-cold-chain/reeferiotsimulator/tree/master
    image.opencontainers.org/url: https://github.ibm.com/vaccine-cold-chain/reeferiotsimulator
    stack.appsody.dev/authors: Chris Bailey <cnbailey@gmail.com>, Henry Nash <henry.nash@uk.ibm.com>
    stack.appsody.dev/configured: docker.io/appsody/python-flask:0.2.1
    stack.appsody.dev/created: "2020-01-10T10:01:07Z"
    stack.appsody.dev/description: Flask web Framework for Python
    stack.appsody.dev/digest: sha256:712ed414c7df9c3e37336b183bfde8e917fdcff50daaa11f600a8d68ab3801df
    stack.appsody.dev/documentation: https://github.com/appsody/stacks/tree/master/incubator/python-flask/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: d8bb65bb0eb5950b124d3f10468475bd84ecf8ee
    stack.appsody.dev/source: https://github.com/appsody/stacks/tree/master/incubator/python-flask/image
    stack.appsody.dev/tag: docker.io/appsody/python-flask:0.2.1
    stack.appsody.dev/title: Python Flask
    stack.appsody.dev/url: https://github.com/appsody/stacks/tree/master/incubator/python-flask
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: vaccine-cold-chain-monitoring
    image.opencontainers.org/title: vaccine-reefer-simulator
    stack.appsody.dev/id: python-flask
    stack.appsody.dev/version: 0.2.1
  name: vaccine-reefer-simulator
spec:
  applicationImage: ibmcase/vaccine-reefer-simulator:v1.0.0
  createKnativeService: false
  env:
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: reefer-simul-cmap
  - name: KAFKA_MAIN_TOPIC
    valueFrom:
      configMapKeyRef:
        key: kafka-topic
        name: reefer-simul-cmap
  - name: KAFKA_USER
    valueFrom:
      configMapKeyRef:
        key: kafka-user
        name: reefer-simul-cmap
  - name: KAFKA_PWD
    valueFrom:
      secretKeyRef:
        key: password
        name: eventstreams-api-key
  - name: KAFKA_CERT
    valueFrom:
      configMapKeyRef:
        key: kafka-cert-path
        name: reefer-simul-cmap
  expose: true
  imagePullPolicy: Always
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: vaccine-reefer-simulator
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: python-flask
  version: 1.0.0
  volumeMounts:
  - mountPath: /certs
    name: eventstreams-pem
  volumes:
  - name: eventstreams-pem
    secret:
      optional: true
      secretName: eventstreams-pem
status: {}
