apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: reeferiotsimulator
spec:
  applicationSelector:
    group: apps
    resource: deployments
    resourceRef: reeferiotsimulator
    version: v1
  backingServiceSelector:
    group: kafka.strimzi.io
    kind: Kafka
    resourceRef: kafka
    version: v1beta1
  customEnvVar:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: |-
      {{- range .status.listeners -}}
        {{- if and (eq .type "plain") (gt (len .addresses) 0) -}}
          {{- with (index .addresses 0) -}}
            {{ .host }}:{{ .port }}
          {{- end -}}
        {{- end -}}
      {{- end -}}
