---
# Source: refrigerated-container-simulator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-refrigerated-container-simulator
  labels:
    app.kubernetes.io/name: refrigerated-container-simulator
    helm.sh/chart: refrigerated-container-simulator-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: refrigerated-container-simulator
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: refrigerated-container-simulator
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: refrigerated-container-simulator
          image: "ibmcase/refrigerated-container-simulator:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            null
            
      env:
          - name: PORT
            value: ""
          - name: APPLICATION_NAME
            value: "release-name"
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: "kafka-brokers"
                key: brokers
          - name: TELEMETRY_TOPIC
            value: "reeferTelemetries"
          - name: CONTAINER_TOPIC
            value: "containers"
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "eventstreams-apikey"
                key: binding
